<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'HighchartOption'                => __DIR__ . '/HighchartOption.php',
  'HighchartsPHP\HighchartsJsExpr' => __DIR__ . '/HighchartsJsExpr.php',
  'HighchartJsExpr'                => __DIR__ . '/HighchartJsExpr.php',
  'HighchartsPHP\HighchartsOption' => __DIR__ . '/HighchartsOption.php',
  'HighchartsPHP\Highcharts'       => __DIR__ . '/Highcharts.php',
  'Highchart'                      => __DIR__ . '/Highchart.php',
);
